name: "Build"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build the Microservice
        run: docker build ./ --tag "ghcr.io/$GITHUB_REPOSITORY:latest"

      - name: Push the Microservice to the GHCR
        run: docker push "ghcr.io/$GITHUB_REPOSITORY:latest"
